spring:
  application:
    name: job-tracker-app

app:
  cors:
    allowed-origins: []

  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: ${MONGODB_DB}

aws:
  region: ${AWS_REGION}
  credentials:
    accessKey: ${AWS_ACCESS_KEY_ID}
    secretKey: ${AWS_SECRET_ACCESS_KEY}
  s3:
    bucket: ${AWS_S3_BUCKET}
  ses:
    fromEmail: ${AWS_SES_FROM_EMAIL}

auth0:
  domain: ${AUTH0_DOMAIN}
  clientId: ${AUTH0_CLIENT_ID}
  clientSecret: ${AUTH0_CLIENT_SECRET}
  audience: https://jobtracker-api

jobs:
  rapidapiKey: ${RAPIDAPI_KEY}
  seedEnabled: ${JOB_SEED_ENABLED}

server:
  port: 8080

---
spring:
  config:
    activate:
      on-profile: dev

  data:
    mongodb:
      auto-index-creation: true

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.jobtracker: DEBUG

---
spring:
  config:
    activate:
      on-profile: prod

logging:
  level:
    root: WARN
    com.jobtracker: INFO
