spring:
  profiles:
    active: dev 
  application:
    name: job-tracker-app

  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: ${MONGODB_DB}

app:
  cors:
    allowed-origins: "http://localhost:3000"

aws:
  region: ${AWS_REGION}
  credentials:
    accessKey: ${AWS_ACCESS_KEY_ID}
    secretKey: ${AWS_SECRET_ACCESS_KEY}
  s3:
    bucket: ${AWS_S3_BUCKET}
  ses:
    fromEmail: ${AWS_SES_FROM_EMAIL}

auth0:
  domain: ${AUTH0_DOMAIN}
  
  # For user authentication (login) - Use SPA credentials
  authentication:
    client-id: ${AUTH0_SPA_CLIENT_ID}
    client-secret: ${AUTH0_SPA_CLIENT_SECRET}
    audience: https://jobtracker-api
  
  # For Management API (creating/managing users) - Use M2M credentials
  management:
    client-id: ${AUTH0_M2M_CLIENT_ID}
    client-secret: ${AUTH0_M2M_CLIENT_SECRET}
    audience: https://dev-ef81elo8soa00i4u.ca.auth0.com/api/v2/

jobs:
  rapidapiKey: ${RAPIDAPI_KEY}
  seedEnabled: ${JOB_SEED_ENABLED}

server:
  port: 8080

---

spring:
  config:
    activate:
      on-profile: dev
  data:
    mongodb:
      auto-index-creation: true

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.jobtracker: DEBUG

---

spring:
  config:
    activate:
      on-profile: prod

logging:
  level:
    root: WARN
    com.jobtracker: INFO
